[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/favicon*"
  to = "/favicon:splat"
  status = 200

[[redirects]]
  from = "/icon-*.png"
  to = "/icon-:splat.png"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
