# Allow static files to load (VERY IMPORTANT)

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

[[redirects]]
  from = "/icon-192.png"
  to = "/icon-192.png"
  status = 200

[[redirects]]
  from = "/icon-512.png"
  to = "/icon-512.png"
  status = 200

# Standard SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
